title: Nokia Webscale Reference List
description: Quick prototype reference page for links to products relevant to Webscale customers
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme